# 配置端口号 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003
#server:
#  port: 8001

# 服务名
spring:
  application:
    name: product-data-service

# 配置注册中心地址  与eurekaServer中的配置一致
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
