# 配置注册中心地址  与eurekaServer中的配置一致
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    # 服务名
    name: config-server
  cloud:
    config:
      # 表示分支
      label: master
      server:
        git:
          # 表示git地址
          uri: https://github.com/how2j/springcloudConfig/
          # 表示目录
          searchPaths: respo
